---
development:
  cloud_name: dqo5zfv4u
  api_key: '225345727686215'
  api_secret: lAvm-lXgKq5_edstWBim6H4G6hA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dqo5zfv4u
  api_key: '225345727686215'
  api_secret: lAvm-lXgKq5_edstWBim6H4G6hA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dqo5zfv4u
  api_key: '225345727686215'
  api_secret: lAvm-lXgKq5_edstWBim6H4G6hA
  enhance_image_tag: true
  static_file_support: false
